os: linux
dist: ubuntu
language: python
cache: pip
python: 3.8

stages:
  - test
  - staging
  - bastion
  - prod
  - deploy

jobs:
  include:
  - name: Linting
    stage: test
    if: branch IN (master, staging)
    before_script:
      - git remote set-branches --add origin $TRAVIS_BRANCH
      - git fetch
    script:
      - source ci/find_changed_files.sh
      - ci/cfn_lint.sh

  - name: BuildStaging
    stage: staging
    env: ENVIRONMENT="staging"
    if: branch = staging
    script:
      - echo "Build staging"
      - python ci/apply_sam_workflow_pr.py

  - name: BuildBastion
    stage: bastion
    env: ENVIRONMENT="bastion"
    if: branch = master
    script:
      - python ci/test_sam_workflow_pr.py

  - name: BuildProd
    stage: prod
    env: ENVIRONMENT="prod"
    if: branch = master
    script:
      - python ci/test_sam_workflow_pr.py

  - name: Deploy
    stage: deploy
    if: branch IN (master, staging)
    script:
      - echo "Deploy"
    deploy:
      - provider: script
        edge: true
        script: ci/deploy.sh staging
        on:
          branch: staging

      - provider: script
        edge: true
        script: ci/deploy.sh bastion
        on:
          branch: master

      - provider: script
        edge: true
        script: ci/deploy.sh prod
        on:
          branch: master
install:
  - echo "Install dependencies"
  - sudo chmod +x ci/*
  - ci/install_dependencies.sh
  - ci/aws_auth.sh
