version=0.1

[staging.build.parameters]
profile="staging"
use_container=true
skip_pull_image=true

[staging.package.parameters]
profile="staging"
s3_bucket="564188978527-artefacts-bastion"
s3_prefix="lake-ingest-understat-staging"

[staging.deploy.parameters]
profile="staging"
stack_name="lake-ingest-understat-staging"
region="eu-west-1"
s3_bucket="564188978527-artefacts-bastion"
s3_prefix="lake-ingest-understat-staging"
capabilities=["CAPABILITY_NAMED_IAM", "CAPABILITY_AUTO_EXPAND"]
parameter_overrides=[
    "Environment=staging",
    "RegistryAlias=e8e9g5w6",
    "ImageTag=v0.1.2-alpha.3",
    "ImageName=understat-crawler"
]

[prod.build.parameters]
profile="prod"
use_container=true
skip_pull_image=true

[prod.package.parameters]
profile="prod"
s3_bucket="564188978527-artefacts-bastion"
s3_prefix="lake-ingest-understat-prod"

[prod.deploy.parameters]
profile="prod"
stack_name="lake-prod"
region="eu-west-1"
s3_bucket="564188978527-artefacts-bastion"
s3_prefix="lake-ingest-understat-prod"
capabilities=["CAPABILITY_NAMED_IAM", "CAPABILITY_AUTO_EXPAND"]
parameter_overrides=[
    "Environment=prod",
    "RegistryAlias=e8e9g5w6",
    "JobDefinitionName=understat-crawler",
    "ImageTag=v0.1.2-alpha.3",
    "ImageName=understat-crawler"
]

