AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Ingest data from understat.com into lake

Parameters:

  Environment:
    Description: The account where the resources are being created
    Type: String
    Default: staging
    AllowedValues:
      - staging
      - prod

Resources:

  IngestUnderstatFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action: sts:AssumeRole
            Principal:
              Service: lambda.amazonaws.com
            Effect: Allow
      Policies:
        - PolicyName: lambdaexecution
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
        - PolicyName: sqs
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                  - sqs:ChangeMessageVisibility
                Resource: !GetAtt IngestUnderstatQueue.Outputs.QueueArn
        - PolicyName: kinsesis
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - firehose:PutRecord
                Resource:
                  Fn::ImportValue: !Sub lake-${Environment}:FootballUnderstatDeliveryStreamArn

  IngestUnderstatFunction:
    Type: AWS::Serverless::Application
    Properties:
      Location: ../../../lambda/base/template.yaml
      Parameters:
        Environment: !Ref Environment
        FunctionName: ingest-understat
        CodeUri: ../../lake/ingest/understat/download_html/
        Description: Download full html page and push to lake
        MemorySize: 128
        Timeout: 30
        Role: !GetAtt IngestUnderstatFunctionRole.Arn
        FirehoseDeliveryStream:
          Fn::ImportValue: !Sub lake-${Environment}:FootballUnderstatDeliveryStream

  IngestUnderstatQueue:
    Type: AWS::Serverless::Application
    Properties:
      Location: ../../../sqs/base/template.yaml
      Parameters:
        Environment: !Ref Environment
        QueueName: ingest-understat
        Timeout: 60

  IngestUnderstatTrigger:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: !GetAtt IngestUnderstatQueue.Outputs.QueueArn
      FunctionName: !GetAtt IngestUnderstatFunction.Outputs.FunctionName


Outputs:

  IngestUnderstatFunctionName:
    Value: !GetAtt IngestUnderstatFunction.Outputs.FunctionName
    Export:
      Name: !Sub ${AWS::StackName}:IngestUnderstatFunctionName

  IngestUnderstatFunctionArn:
    Value: !GetAtt IngestUnderstatFunction.Outputs.FunctionArn
    Export:
      Name: !Sub ${AWS::StackName}:IngestUnderstatFunctionArn