AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  brendan:
    Type: AWS::IAM::User
    Properties:
      Groups:
        - Developers
        - IAMAdmins
        - BaseUsers
      LoginProfile:
        Password: "T:MUtot=H*joEYnx!&"
        PasswordResetRequired: true
      UserName: brendan

  cicd:
    Type: AWS::IAM::User
    Properties:
      Groups:
        - Deployers
        - IAMAdmins
        - BaseUsers
      UserName: cicd