AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:

  BrendanDefaultPassword:
    Type: String
    Default: /iam/user/brendan-default-password

Resources:
  brendan:
    Type: AWS::IAM::User
    Properties:
      Groups:
        - Developers
        - IAMAdmins
        - BaseUsers
      LoginProfile:
        Password: !Join
          - ''
          - - '{'
            - '{'
            - 'resolve:'
            - 'ssm:'
            - !Ref BrendanDefaultPassword
            - ':'
            - '1'
            - '}'
            - '}'
        PasswordResetRequired: true
      UserName: brendan

  cicd:
    Type: AWS::IAM::User
    Properties:
      Groups:
        - Deployers
        - IAMAdmins
        - BaseUsers
      UserName: cicd
