AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Public ECR repository for container(s) used for ingesting understat data

Resources:

  CrawlerECRRepository:
    Type: AWS::ECR::PublicRepository
    Properties:
      RepositoryName: understat-crawler

