AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  Deploy Mlflow as an ECS service, along with all its required resources.

Parameters:

  EnvironmentName:
    Type: String
    Description: >-
      An environment name that will be suffixed to all resources.
      Example: dev, stage, utils, prod.

  MlflowImageUrl:
    Type: String
    Description: The url of the Mlflow docker image to deploy.

  MlflowContainerCpu:
    Type: Number
    Default: 128
    Description: How much CPU to give the container. 1024 is 1 CPU.

  MlflowContainerMemory:
    Type: Number
    Default: 512
    Description: How much memory in megabytes to give the container.

Resources:

###############################################################################
# \/              Mlflow S3 bucket & access role configuration             \/ #
###############################################################################

  MlflowBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "trackman-mlflow-${EnvironmentName}"
    DeletionPolicy: Retain

  MlflowRole:
    Type: AWS::IAM::Role
    DependsOn:
      - MlflowBucket
    Properties:
      RoleName : !Sub "mlflow-${EnvironmentName}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: ecs
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - cloudwatch:DescribeAlarmsForMetric
                  - cloudwatch:ListMetrics
                  - cloudwatch:GetMetricStatistics
                  - cloudwatch:GetMetricData
                  - ec2:DescribeTags
                  - ec2:DescribeInstances
                  - ec2:DescribeRegions
                  - tag:GetResources
                Resource: "*"
        - PolicyName: mlflow-bucket
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                Resource:
                  - !GetAtt MlflowBucket.Arn
                  - Fn::Join:
                    - "/"
                    - - !GetAtt MlflowBucket.Arn
                      - "*"

###############################################################################
# /\              Mlflow S3 bucket & access role configuration             /\ #
#                                                                             #
# \/                 Mlflow load-balancer configuration                    \/ #
###############################################################################

  MlflowSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub "mlflow-${EnvironmentName}"
      GroupDescription: Security group for Mlflow elastic loadbalancer
      VpcId:
        Fn::ImportValue: !Sub "VPC-${EnvironmentName}"

  ECSSecurityGroupRuleAdd:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: tcp
      FromPort: 0
      ToPort: 65535
      SourceSecurityGroupId:
        Fn::GetAtt:
        - MlflowSecurityGroup
        - GroupId
      GroupId:
        Fn::ImportValue: !Sub "EcsHostSecurityGroup-${EnvironmentName}"

  MlflowLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub "mlflow-${EnvironmentName}"
      Scheme: internet-facing
      Type: application
      Subnets:
        - Fn::ImportValue: !Sub "PublicSubnet1-${EnvironmentName}"
        - Fn::ImportValue: !Sub "PublicSubnet2-${EnvironmentName}"
      SecurityGroups:
        - Fn::ImportValue: !Sub "OfficeSecurityGroup-${EnvironmentName}"
        - !Ref MlflowSecurityGroup

  MlflowTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub "mlflow-${EnvironmentName}"
      HealthCheckIntervalSeconds: 6
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      Name: !Sub "mlflow-${EnvironmentName}"
      Port: 80
      Protocol: HTTP
      UnhealthyThresholdCount: 2
      VpcId:
        Fn::ImportValue: !Sub "VPC-${EnvironmentName}"
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: 30

  MlflowListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    DependsOn:
      - MlflowLoadBalancer
      - MlflowTargetGroup
    Properties:
      DefaultActions:
        - TargetGroupArn: !Ref MlflowTargetGroup
          Type: forward
      LoadBalancerArn: !Ref MlflowLoadBalancer
      Port: 80
      Protocol: HTTP

###############################################################################
# /\                 Mlflow load-balancer configuration                    /\ #
#                                                                             #
# \/                  Mlflow ECS service configuration                     \/ #
###############################################################################

  MlflowLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/ecs/mlflow-${EnvironmentName}"
      RetentionInDays: 90

  MlflowTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    DependsOn:
      - MlflowLogGroup
    Properties:
      Cpu: !Ref MlflowContainerCpu
      Family: !Sub "mlflow-${EnvironmentName}"
      Memory: !Ref MlflowContainerMemory
      TaskRoleArn: !GetAtt MlflowRole.Arn
      ContainerDefinitions:
        - Name: !Sub "mlflow-${EnvironmentName}"
          Cpu: !Ref MlflowContainerCpu
          Environment:
            - Name: MLFLOW_S3_BUCKET_NAME
              Value: !Ref MlflowBucket
            - Name: MLFLOW_BACKEND_STORE_URI
              Value: /opt/mlflow
          Image: !Ref MlflowImageUrl
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref MlflowLogGroup
              awslogs-region: eu-central-1
              awslogs-stream-prefix: mlflow
          Memory: !Ref MlflowContainerMemory
          MountPoints:
            - ContainerPath: /opt/mlflow
              SourceVolume: backend-store
          PortMappings:
            - ContainerPort: 5000
      Volumes:
        - Name: backend-store
          DockerVolumeConfiguration:
            Autoprovision: true
            Driver: local
            Scope: shared

  MlflowService:
    Type: AWS::ECS::Service
    DependsOn:
      - MlflowListener
      - MlflowTaskDefinition
    Properties:
      ServiceName: !Sub "mlflow-${EnvironmentName}"
      Cluster:
        Fn::ImportValue: !Sub "ECSCluster-${EnvironmentName}"
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 75
      DesiredCount: 1
      TaskDefinition: !Ref MlflowTaskDefinition
      LoadBalancers:
        - ContainerName: !Sub "mlflow-${EnvironmentName}"
          ContainerPort: 5000
          TargetGroupArn: !Ref MlflowTargetGroup

###############################################################################
# /\                  Mlflow ECS service configuration                     /\ #
#                                                                             #
# \/                      Mlflow alerts configuration                      \/ #
###############################################################################

  MlflowLowCpuUsageAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "mlflow-low_cpu-${EnvironmentName}"
      AlarmDescription: CPUUtilization low
      MetricName: CPUUtilization
      Namespace: AWS/ECS
      Dimensions:
        - Name: ServiceName
          Value: !Ref MlflowService
      Statistic: Average
      Period: 60
      EvaluationPeriods: 1
      Threshold: 20
      ComparisonOperator: LessThanOrEqualToThreshold

  MlflowHighCpuUsageAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "mlflow-high_cpu-${EnvironmentName}"
      AlarmDescription: CPUUtilization high
      MetricName: CPUUtilization
      Namespace: AWS/ECS
      Dimensions:
        - Name: ServiceName
          Value: !Ref MlflowService
      Statistic: Average
      Period: 60
      EvaluationPeriods: 1
      Threshold: 70
      ComparisonOperator: GreaterThanOrEqualToThreshold
