version=0.1

[utils]

[utils.build]
[utils.build.parameters]
profile="utils"
skip_pull_image=true
use_container=true
cached=true

[utils.package]
[utils.package.parameters]
profile="utils"
region="eu-central-1"
s3_bucket="trackman-artifacts"
# force_upload=true

[utils.deploy]
[utils.deploy.parameters]
stack_name="mlflow-utils"
capabilities=["CAPABILITY_NAMED_IAM", "CAPABILITY_AUTO_EXPAND"]
region="eu-central-1"
profile="utils"
# parameter_overrides=["EnvironmentName=utils", "MlflowImageUrl=555450050944.dkr.ecr.us-east-1.amazonaws.com/mlflow:afa-2020-02-06-13-52"]
parameter_overrides=["EnvironmentName=utils", "MlflowImageUrl=555450050944.dkr.ecr.us-east-1.amazonaws.com/mlflow:latest"]
# s3_bucket="trackman-artifacts"

