version: 2.1

commands:

  setup:
    description: Checkout & Get name of target branch
    steps:
      - checkout
      - run:
          name: Get name of target branch
          command: |
            if [[ ! -z ${CIRCLE_PULL_REQUEST} ]]
            then
              curl -L "https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64" \
                -o jq
              chmod u+x jq
              pr_number="${CIRCLE_PULL_REQUEST##*/}"
              url="https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/pulls/${pr_number}"
              export TARGET_BRANCH=$(\
                  curl "$url" \
                  -H "Authorization: $GITHUB_TOKEN" \
                      | ./jq '.base.ref' \
                      |  tr -d '"' \
                  )
              if [[  "$TARGET_BRANCH" = "master" || "$TARGET_BRANCH" = "staging" ]]
              then
                echo "Target branch - $TARGET_BRANCH"
                echo "$TARGET_BRANCH" > /tmp/target_branch
              else
                echo "Target branch - $TARGET_BRANCH"
                echo "Cannot continue build on this branch"
                exit 1
              fi
            else
              echo "Build is not for a PR. Using current branch as the target branch"
              echo "$CIRCLE_BRANCH" > /tmp/target_branch
            fi

  pr_or_push:
    description: Check if the current build is happening because of a PR
    steps:
      - run:
          name: Check if PR
          command: |
            if [[ ! -z ${CIRCLE_PULL_REQUEST} ]]
            then
              echo "Build is for pr ${CIRCLE_PR_NUMBER}"
              echo "pr" > /tmp/pr_or_push
            else
              echo "Build is not for a PR"
              echo "push" > /tmp/pr_or_push
            fi

  install_dependencies:
    description: Install all dependencies
    parameters:
      allowed_branch:
        default: staging
        type: string
    steps:
      - run:
          name: Install dependencies
          command: |
            ./ci/install_dependencies.sh
            venv/bin/python -m pip install toml


jobs:

  test:
    docker:
      - image: cimg/python:3.9
    steps:
      - setup
      - install_dependencies
      - run:
          name: Linting
          command: |
            source venv/bin/activate
            which python
            python --version
            . ./ci/find_changed_files.sh  "$(cat /tmp/target_branch)" && ./ci/cfn_lint.sh
      - save_cache:
          key: python-requirements-V1-{{ checksum "dev_requirements.txt" }}
          paths:
            - "~/.cache/pip"

  build:
    docker:
      - image: cimg/python:3.9
    steps:
      - pr_or_push
      - setup
      - restore_cache:
          key: python-requirements-V1-{{ checksum "dev_requirements.txt" }}
      - install_dependencies
      - run:
          name: Build
          command: |
            source venv/bin/activate
            ./ci/aws_auth.sh
            target_branch="$(cat /tmp/target_branch)"
            pr_or_push="$(cat /tmp/pr_or_push)"

            if [[ $target_branch = master ]]
            then
                echo Building bastion ...
                ENVIRONMENT=bastion ./ci/test_sam_workflow_pr.sh master
                echo Building prod ...
                ENVIRONMENT=prod ./ci/test_sam_workflow_pr.sh master
            elif [[ $target_branch = staging ]]
            then
                echo Building staging ...
                ENVIRONMENT=staging ./ci/apply_sam_workflow_pr.sh staging
            else
                echo Can only build master or staging. Exiting.
                exit 1
            fi

  deploy:
    docker:
      - image: cimg/python:3.9
    steps:
      - pr_or_push
      - setup
      - restore_cache:
          key: python-requirements-V1-{{ checksum "dev_requirements.txt" }}
      - install_dependencies
      - run:
          name: Deploy
          command: |
            source venv/bin/activate
            ./ci/aws_auth.sh
            target_branch="$(cat /tmp/target_branch)"
            pr_or_push="$(cat /tmp/pr_or_push)"

            if [[ $pr_or_push = pr ]]
            then
                echo Only deploy merges. Exiting.
                exit 0
            fi


            if [[ $target_branch = master ]]
            then
                echo Deploying bastion ...
                ci/deploy.sh bastion
                echo Deploying prod ...
                ci/deploy.sh prod
            elif [[ $target_branch = staging ]]
            then
                echo Deploying staging ...
                ci/deploy.sh staging
            else
                echo Can only deploy master or staging. Exiting.
                exit 1
            fi

workflows:
    version: 2
    test-build-deploy:
      jobs:
        - test
        - build:
            requires:
              - test
        - deploy:
            requires:
              - test
              - build

