version=0.1

[staging.build.parameters]
profile="staging"
use_container=true
skip_pull_image=true

[staging.package.parameters]
profile="staging"
s3_bucket="564188978527-artefacts-bastion"
s3_prefix="jenkins-staging"

[staging.deploy.parameters]
profile="staging"
stack_name="jenkins-staging"
region="eu-west-1"
s3_bucket="564188978527-artefacts-bastion"
s3_prefix="jenkins-staging"
capabilities=["CAPABILITY_NAMED_IAM"]
parameter_overrides=[
    "Environment=staging",
    "JenkinsImageUrl=public.ecr.aws/e5d2j4d8/jenkins:latest",
    "JenkinsContainerCpu=512",
    "JenkinsContainerMemory=1024",
    "Enable=false"
]

[prod.build.parameters]
profile="prod"
use_container=true
skip_pull_image=true

[prod.package.parameters]
profile="prod"
s3_bucket="564188978527-artefacts-bastion"
s3_prefix="jenkins-prod"

[prod.deploy.parameters]
profile="prod"
stack_name="jenkins-prod"
region="eu-west-1"
s3_bucket="564188978527-artefacts-bastion"
s3_prefix="jenkins-prod"
capabilities=["CAPABILITY_NAMED_IAM"]
parameter_overrides=["Environment=prod", "JenkinsImageUrl=public.ecr.aws/e5d2j4d8/jenkins:latest"]
