AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Data lake infrastructure

Parameters:

  BucketName:
    Type: String

  Environment:
    Description: The account where the resources are being created
    Type: String
    Default: staging
    AllowedValues:
      - bastion
      - staging
      - prod

  DeletionPolicy:
    Description: The deletion policy for the bucket
    Type: String
    Default: Retain

  Versioning:
    Description: Versioning configuration for the bucket
    Type: String
    Default: Enabled

  AccessControl:
    Description: Access control for the bucket
    Type: String
    Default: Private

Conditions:

  ProdResources:
   !Equals
   - !Ref Environment
   - prod

Resources:

  Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: !Ref DeletionPolicy
    UpdateReplacePolicy: Retain
    Properties:
      AccessControl: !Ref AccessControl
      BucketName: !Sub "${AWS::AccountId}-${BucketName}-${Environment}"
      LifecycleConfiguration:
        Rules:
          - Id: lifecycle
            NoncurrentVersionExpirationInDays:
              !If
              - ProdResources
              - 30
              - 7
            Status: Enabled
            ExpirationInDays:
              !If
              - ProdResources
              - 30
              - !Ref AWS::NoValue
      VersioningConfiguration:
        Status: !Ref Versioning

Metadata:
  cfn-lint:
    config:
      ignore_checks:
      - E0001 # https://stackoverflow.com/questions/34286395