AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  Base template for creating an s3 bucket (version 2)

Parameters:

  BucketName:
    Type: String

  Environment:
    Description: The account where the bucket is being created
    Type: String
    Default: staging
    AllowedValues:
      - bastion
      - staging
      - prod

  Versioning:
    Description: Versioning configuration for the bucket
    Type: String
    Default: Enabled

  AccessControl:
    Description: Access control for the bucket
    Type: String
    Default: Private

  Application:
    Description: Name of application. Used for tagging
    Type: String

Resources:

  Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      AccessControl: !Ref AccessControl
      BucketName: !Sub ${AWS::AccountId}-${AWS::Region}-${BucketName}-${Environment}
      VersioningConfiguration:
        Status: !Ref Versioning
      Tags:
        - Key: application
          Value: !Ref Application

Outputs:

  BucketName:
    Value: !Ref Bucket
    Export:
      Name: !Sub ${AWS::StackName}:BucketName

  BucketArn:
    Value: !GetAtt Bucket.Arn
    Export:
      Name: !Sub ${AWS::StackName}:BucketArn
