AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Data lake infrastructure

Parameters:

  BucketName:
    Type: String

  Environment:
    Description: The account where the resources are being created
    Type: String
    Default: staging
    AllowedValues:
      - bastion
      - staging
      - prod

  DeletionPolicy:
    Description: The deletion policy for the bucket
    Type: String
    Default: Retain

  Versioning:
    Description: Versioning configuration for the bucket
    Type: String
    Default: Enabled

  AccessControl:
    Description: Access control for the bucket
    Type: String
    Default: Private


Mappings:
  EnvironmentConfig:
    staging:
      VersionExpiration: 7
      LifecycleDays: 30
      lifecycle-staging: Enabled
      lifecycle-prod: Disabled

    prod:
      VersionExpiration: 30
      LifecycleDays: null
      lifecycle-staging: Disabled
      lifecycle-prod: Enabled


Resources:

  Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: !Ref DeletionPolicy
    Properties:
      AccessControl: !Sub AccessControl
      BucketName: !Sub "${AWS::AccountId}-${BucketName}-${Environment}"
      LifecycleConfiguration:
        Rules:
          - Id: lifecycle-staging
            NoncurrentVersionExpirationInDays: !FindInMap
              - EnvironmentConfig
              - !Ref Environment
              - VersionExpiration
            Status: !FindInMap
              - EnvironmentConfig
              - !Ref Environment
              - lifecycle-staging
            ExpirationInDays: !FindInMap
              - EnvironmentConfig
              - !Ref Environment
              - LifecycleDays
          - Id: lifecycle-prod
            NoncurrentVersionExpirationInDays: !FindInMap
              - EnvironmentConfig
              - !Ref Environment
              - VersionExpiration
            Status: !FindInMap
              - EnvironmentConfig
              - !Ref Environment
              - lifecycle-prod
            ExpirationInDays: !FindInMap
              - EnvironmentConfig
              - !Ref Environment
              - LifecycleDays
      VersioningConfiguration:
        Status: !Ref Versioning
