version=0.1

[staging.build.parameters]
profile="staging"
use_container=true
skip_pull_image=true

[staging.package.parameters]
profile="staging"
s3_bucket="564188978527-artefacts-bastion"
s3_prefix="ecs-cluster-staging"

[staging.deploy.parameters]
profile="staging"
stack_name="ecs-cluster-staging"
region="eu-west-1"
s3_bucket="564188978527-artefacts-bastion"
s3_prefix="ecs-cluster-staging"
capabilities=["CAPABILITY_NAMED_IAM"]
parameter_overrides=["Environment=staging"]

[prod.build.parameters]
profile="prod"
use_container=true
skip_pull_image=true

[prod.package.parameters]
profile="prod"
s3_bucket="564188978527-artefacts-bastion"
s3_prefix="ecs-cluster-prod"

[prod.deploy.parameters]
profile="prod"
stack_name="ecs-cluster-prod"
region="eu-west-1"
s3_bucket="564188978527-artefacts-bastion"
s3_prefix="ecs-cluster-prod"
capabilities=["CAPABILITY_NAMED_IAM"]
parameter_overrides=["Environment=prod"]
