version=0.1

[bastion.build.parameters]
profile="bastion"
debug=true
stack_name="iam-roles"
region="eu-west-1"

[bastion.deploy.parameters]
profile="bastion"
stack_name="iam-roles-bastion"
region="eu-west-1"
capabilities="CAPABILITY_NAMED_IAM"
parameter_overrides=["TargetEnvironment=bastion"]

[staging.build.parameters]
profile="staging"
stack_name="iam-roles-staging"
region="eu-west-1"

[staging.deploy.parameters]
profile="staging"
stack_name="iam-roles-staging"
region="eu-west-1"
capabilities="CAPABILITY_NAMED_IAM"
parameter_overrides=["TargetEnvironment=staging"]

[prod.build.parameters]
profile="prod"
debug=false
stack_name="iam-roles-prod"
region="eu-west-1"

[prod.deploy.parameters]
profile="prod"
stack_name="iam-roles-prod"
region="eu-west-1"
capabilities="CAPABILITY_NAMED_IAM"
parameter_overrides=["TargetEnvironment=prod"]
