AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Cross account roles

Parameters:
  TargetEnvironment:
    Description: The account where the roles are being created
    Type: String
    Default: staging
    AllowedValues:
      - bastion
      - staging
      - prod

  SourceEnvironment:
    Description: The account which has permission to assume the role
    Type: String
    Default: bastion
    AllowedValues:
      - bastion

Mappings:
  AccountId:
    staging:
      accountid: 626964907981
    prod:
      accountid: 875094265107
    bastion:
      accountid: 564188978527

Resources:

  DeveloperAccessRole:
    Type: AWS::IAM::Role
    Properties:
      Description: A role which grants developer access
      Path: /
      RoleName: !Sub DeveloperAccess-${TargetEnvironment}
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              AWS:
                Fn::Join:
                  - ':'
                  - - arn
                    - Ref: AWS::Partition
                    - 'iam:'
                    - Fn::FindInMap:
                      - AccountId
                      - Ref: SourceEnvironment
                      - accountid
                    - root
      Policies:
        - PolicyName: cloudformation
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: cloudformation:*
                Resource: '*'
        - PolicyName: resources
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sts:GetServiceBearerToken
                  - s3:*
                  - lambda:*
                  - sqs:*
                  - sns:*
                  - cloudwatch:*
                  - apigateway:*
                  - batch:*
                  - cloudfront:*
                  - cloudtrail:*
                  - cloudwatch:*
                  - dynamodb:*
                  - ecr:*
                  - ecr-public:*
                  - ecs:*
                  - eventbridge:*
                  - firehose:*
                  - kinesis:*
                  - glacier:*
                  - glue:*
                  - rds:*
                  - redshift:*
                  - route53:*
                  - stepfunctions:*
                  - ssm:*
                  - logs:*
                Resource: '*'
        - PolicyName: iam
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - iam:GetPolicyVersion
                  - iam:GetAccountPasswordPolicy
                  - iam:ListRoleTags
                  - iam:ListServerCertificates
                  - iam:GenerateServiceLastAccessedDetails
                  - iam:CreateRole
                  - iam:AttachRolePolicy
                  - iam:ListServiceSpecificCredentials
                  - iam:ListSigningCertificates
                  - iam:ListVirtualMFADevices
                  - iam:ListSSHPublicKeys
                  - iam:SimulateCustomPolicy
                  - iam:DetachRolePolicy
                  - iam:SimulatePrincipalPolicy
                  - iam:ListAttachedRolePolicies
                  - iam:ListOpenIDConnectProviderTags
                  - iam:ListSAMLProviderTags
                  - iam:ListRolePolicies
                  - iam:GetAccountAuthorizationDetails
                  - iam:GetCredentialReport
                  - iam:ListPolicies
                  - iam:GetServerCertificate
                  - iam:GetRole
                  - iam:ListSAMLProviders
                  - iam:GetPolicy
                  - iam:GetAccessKeyLastUsed
                  - iam:ListEntitiesForPolicy
                  - iam:DeleteUserPolicy
                  - iam:DeleteRole
                  - iam:UpdateRoleDescription
                  - iam:TagPolicy
                  - iam:GetUserPolicy
                  - iam:ListGroupsForUser
                  - iam:GetGroupPolicy
                  - iam:GetOpenIDConnectProvider
                  - iam:GetRolePolicy
                  - iam:GetAccountSummary
                  - iam:GenerateCredentialReport
                  - iam:UntagRole
                  - iam:GetServiceLastAccessedDetailsWithEntities
                  - iam:TagRole
                  - iam:ListPoliciesGrantingServiceAccess
                  - iam:DeletePolicy
                  - iam:ListInstanceProfileTags
                  - iam:ListMFADevices
                  - iam:GetServiceLastAccessedDetails
                  - iam:GetGroup
                  - iam:GetContextKeysForPrincipalPolicy
                  - iam:GetOrganizationsAccessReport
                  - iam:GetServiceLinkedRoleDeletionStatus
                  - iam:ListInstanceProfilesForRole
                  - iam:GenerateOrganizationsAccessReport
                  - iam:DeleteRolePolicy
                  - iam:ListAttachedUserPolicies
                  - iam:ListAttachedGroupPolicies
                  - iam:ListPolicyTags
                  - iam:CreatePolicyVersion
                  - iam:GetSAMLProvider
                  - iam:ListAccessKeys
                  - iam:GetInstanceProfile
                  - iam:ListGroupPolicies
                  - iam:GetSSHPublicKey
                  - iam:ListRoles
                  - iam:ListUserPolicies
                  - iam:ListInstanceProfiles
                  - iam:CreatePolicy
                  - iam:GetContextKeysForCustomPolicy
                  - iam:ListPolicyVersions
                  - iam:ListOpenIDConnectProviders
                  - iam:ListServerCertificateTags
                  - iam:ListAccountAliases
                  - iam:UntagPolicy
                  - iam:ListUsers
                  - iam:UpdateRole
                  - iam:GetUser
                  - iam:ListGroups
                  - iam:ListMFADeviceTags
                  - iam:GetLoginProfile
                  - iam:DeletePolicyVersion
                  - iam:ListUserTags
                  - iam:PutRolePolicy
                  - iam:PassRole
                Resource: '*'

  ReadOnlyAccess:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: ReadOnlyAccess-${TargetEnvironment}
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              AWS:
                Fn::Join:
                  - ':'
                  - - arn
                    - Ref: AWS::Partition
                    - 'iam:'
                    - Fn::FindInMap:
                      - AccountId
                      - Ref: SourceEnvironment
                      - accountid
                    - root
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/ReadOnlyAccess

  IAMAdminRole:
    Type: AWS::IAM::Role
    Properties:
      Description: A role which grants full IAM permissions
      Path: /
      RoleName:
        Fn::Sub: IAMAdmin-${TargetEnvironment}
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              AWS:
                Fn::Join:
                  - ':'
                  - - arn
                    - Ref: AWS::Partition
                    - 'iam:'
                    - Fn::FindInMap:
                      - AccountId
                      - Ref: SourceEnvironment
                      - accountid
                    - root
      Policies:
        - PolicyName: "cloudformation"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "cloudformation:*"
                Resource: "*"
        - PolicyName: "iam"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "iam:*"
                  - "ssm:*"
                  - "s3:*"
                Resource: "*"

  # TODO: Move this to the stack with the resources bucket
  BastionBucketAccess:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Grant access to buckets in the bastion account
      ManagedPolicyName: BastionBucketAccess
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: s3:*
            Resource:
              Fn::Join:
                - ':'
                - - arn
                  - Ref: AWS::Partition
                  - s3
                  - ':'
                  - Fn::Join:
                    - '-'
                    - - Fn::FindInMap:
                        - AccountId
                        - bastion
                        - accountid
                      - artefacts
                      - bastion/*
      Roles:
        - Ref: DeveloperAccessRole

Outputs:

  DeveloperAccessRoleArn:
    Description: ARN of the Developer IAM role
    Value:
      Fn::GetAtt:
        - DeveloperAccessRole
        - Arn
    Export:
      Name:
        Fn::Join:
          - ':'
          - - Ref: AWS::StackName
            - DeveloperAccessRoleArn

  DeveloperAccessRoleName:
    Description: Name of the Developer IAM role
    Value:
      Ref: DeveloperAccessRole
    Export:
      Name:
        Fn::Join:
          - ':'
          - - Ref: AWS::StackName
            - DeveloperRoleAccessName

  IAMAdminRoleArn:
    Description: ARN of the IAMAdmin IAM role
    Value:
      Fn::GetAtt:
        - IAMAdminRole
        - Arn
    Export:
      Name:
        Fn::Join:
          - ':'
          - - Ref: AWS::StackName
            - IAMAdminRoleArn

  IAMAdminRoleName:
    Description: Name of the IAMAdmin IAM role
    Value:
      Ref: IAMAdminRole
    Export:
      Name:
        Fn::Join:
          - ':'
          - - Ref: AWS::StackName
            - IAMAdminRoleName

  ReadOnlyAccessArn:
    Description: ARN of the ReadOnlyAccess role
    Value:
      Fn::GetAtt:
        - ReadOnlyAccess
        - Arn
    Export:
      Name:
        Fn::Join:
          - ':'
          - - Ref: AWS::StackName
            - ReadOnlyAccessArn

  ReadOnlyAccessName:
    Description: Name of the ReadOnlyAccess role
    Value:
      Ref: ReadOnlyAccess
    Export:
      Name: !Join
        - ":"
        - - !Ref "AWS::StackName"
          - ReadOnlyAccessName
