version=0.1

[staging.build.parameters]
profile="staging"
use_container=true
skip_pull_image=true

[staging.package.parameters]
profile="staging"
s3_bucket="564188978527-artefacts-bastion"
s3_prefix="ecs-vpc-eu-west-1-staging"

[staging.deploy.parameters]
profile="staging"
stack_name="ecs-vpc-eu-west-1-staging"
region="eu-west-1"
s3_bucket="564188978527-artefacts-bastion"
s3_prefix="ecs-vpc-eu-west-1-staging"
parameter_overrides=["Environment=staging", "ServerCertificateId=ebe5c981-0b03-4791-889b-9536b763a50f"]

[prod.build.parameters]
profile="prod"
use_container=true
skip_pull_image=true

[prod.package.parameters]
profile="prod"
s3_bucket="564188978527-artefacts-bastion"
s3_prefix="ecs-vpc-eu-west-1-prod"

[prod.deploy.parameters]
profile="prod"
stack_name="ecs-vpc-eu-west-1-prod"
region="eu-west-1"
s3_bucket="564188978527-artefacts-bastion"
s3_prefix="ecs-vpc-eu-west-1-prod"
parameter_overrides=["Environment=prod"]
