AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >-
  VPN in eu-west-1

Parameters:

  Environment:
    Description: An environment name that will be prefixed to resource names
    Type: String
    Default: staging
    AllowedValues:
      - bastion
      - staging
      - prod

  ServerCertificateId:
    Description: Client VPN server certificate
    Type: String

Resources:

  ClientVPN:
    Type: AWS::Serverless::Application
    Properties:
      Location: ../base/template.yaml
      Parameters:
        Environment: !Ref Environment
        VpcId:
          Fn::ImportValue:
            !Sub ec2-vpc-${Environment}:VPC
        ServerCertificateId: !Ref ServerCertificateId
        # Can use same certificate for client and server
        ClientCertificateId: !Ref ServerCertificateId
