version=0.1

[staging.build.parameters]
profile="staging"
use_container=true
skip_pull_image=true

[staging.deploy.parameters]
profile="staging"
stack_name="lake-staging"
region="eu-west-1"
parameter_overrides=["Environment=staging"]

[prod.build.parameters]
profile="prod"
use_container=true
skip_pull_image=true

[prod.deploy.parameters]
profile="prod"
stack_name="lake-prod"
region="eu-west-1"
parameter_overrides=["Environment=prod"]
