AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Data lake core infrastructure

Parameters:

  Environment:
    Description: The account where the resources are being created
    Type: String
    Default: staging
    AllowedValues:
      - staging
      - prod

Mappings:

  EnvironmentConfig:
    staging:
      BufferInterval: 60
    prod:
      BufferInterval: 900

Resources:

  ################################ buckets

  AlphaBucket:
    Type: AWS::Serverless::Application
    Properties:
      Location: ../s3/base/template.yaml
      Parameters:
        Environment: !Ref Environment
        BucketName: alpha

  ################################ kinesis

  FootballUnderstatDeliveryStream:
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties:
      DeliveryStreamName: !Sub "alpha-bucket-kinesis-stream-${Environment}"
      ExtendedS3DestinationConfiguration:
        BucketARN: !GetAtt AlphaBucket.Outputs.BucketArn
        CompressionFormat: UNCOMPRESSED
        ErrorOutputPrefix: errors/!{firehose:error-output-type}/sport=football/source=understat/year=!{timestamp:yyyy}/month=!{timestamp:MM}/day=!{timestamp:dd}/
        Prefix: sport=football/source=understat/year=!{timestamp:yyyy}/month=!{timestamp:MM}/day=!{timestamp:dd}/hour=!{timestamp:HH}/
        RoleARN: !GetAtt DeliveryRole.Arn
        BufferingHints:
          IntervalInSeconds:
            !FindInMap
            - EnvironmentConfig
            - !Ref Environment
            - BufferInterval
          SizeInMBs: 128

  DeliveryRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: firehose.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: s3
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
                - Effect: "Allow"
                  Action:
                    - "s3:AbortMultipartUpload"
                    - "s3:GetBucketLocation"
                    - "s3:GetObject"
                    - "s3:ListBucket"
                    - "s3:ListBucketMultipartUploads"
                    - "s3:PutObject"
                  Resource:
                    !Join
                    - "/"
                    - - !GetAtt AlphaBucket.Outputs.BucketArn
                      - "*"

Outputs:

  FootballUnderstatDeliveryStream:
    Value: !Ref FootballUnderstatDeliveryStream
    Export:
      Name: !Sub ${AWS::StackName}:FootballUnderstatDeliveryStream

  FootballUnderstatDeliveryStreamArn:
    Value: !GetAtt FootballUnderstatDeliveryStream.Arn
    Export:
      Name: !Sub ${AWS::StackName}:FootballUnderstatDeliveryStreamArn