AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Data lake core infrastructure

Parameters:

  Environment:
    Description: The account where the resources are being created
    Type: String
    Default: staging
    AllowedValues:
      - bastion
      - staging
      - prod

Resources:

  AlphaBucket:
    Type: AWS::Serverless::Application
    Properties:
      Location: ../s3/base/template.yaml
      Parameters:
        Environment: !Ref Environment
        BucketName: alpha
