AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Data lake core infrastructure

Parameters:

  Environment:
    Description: The account where the resources are being created
    Type: String
    Default: staging
    AllowedValues:
      - staging
      - prod

Resources:

  AlphaBucket:
    Type: AWS::Serverless::Application
    Properties:
      Location: ../s3/base/template.yaml
      Parameters:
        Environment:
          Ref: Environment
        BucketName: alpha

  AlphaBackupBucket:
    Type: AWS::Serverless::Application
    Properties:
      Location: ../s3/base/template.yaml
      Parameters:
        Environment:
          Ref: Environment
        BucketName: alpha-backup

Outputs:

  AlphaBucketArn:
    Value:
      Fn::GetAtt:
        - AlphaBucket
        - Outputs.BucketArn
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}:AlphaBucketArn

  AlphaBackupBucketArn:
    Value:
      Fn::GetAtt:
        - AlphaBackupBucket
        - Outputs.BucketArn
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}:AlphaBackupBucketArn


